server:
  port: 8083

spring:
  application:
    name: inbound-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hof-wms}
    username: ${DB_USER:insightowl}
    password: ${DB_PASSWORD:insightowl}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
